import Head from "next/head";
import { Inter } from "next/font/google";
import Button from "@mui/material/Button";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet" />
      </Head>
      <main>
        <div>
          <Navbar />

          <div className="text-center">Top Seller Carousel</div>
          <div className="text-center">Gallery</div>
          <div className="text-center">Footer</div>
        </div>
      </main>
    </>
  );
}
