import Head from "next/head";
import Gallery from "@/components/Gallery";
import HomeCarousel from "@/components/HomeCarousel";
import { supabase } from "../utils/supabase";

export default function Home({ plants }) {
  console.log(plants, "plants in index");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/dist/output.css" rel="stylesheet" />
      </Head>
      <main>
        <div className="flex flex-col h-screen justify-between">
          <HomeCarousel />
          <Gallery />
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const { data: plants } = await supabase.from("plants").select("*");
  const { data: cart } = await supabase.from("cart").select("*");

  return {
    props: {
      plants,
      cart,
    },
  };
};
